project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Myself.qmd
        text: Myself
      - href: Certifications.qmd
        text: Certifications
      - href: Internships.qmd
        text: Internships
      - href: Mid Project Codes.qmd
        text: Mid Project Codes
      - href: Mid Project Representations.qmd
        text: Mid Project Representations
      - href: Final Project.qmd
        text: Final Project
      - href: Final ProjectCode.qmd
        text: Final ProjectCode

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: true
    

editor: visual

